name: Build and Test
on:
  push:
    branches: [ jazzy ]
  pull_request:
    branches: [ jazzy ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pre install
        run: |
          /usr/bin/bash -c "apt-get update && apt-get install -y libunwind-dev libceres-dev"
      - name: Build simple_localization_toolbox
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: jazzy
          skip-tests: true
      - name: Test slt_interface
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_interface
      - name: Test slt_common
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_common
      - name: Test slt_lidar_odometry
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_lidar_odometry
      - name: Test slt_lidar_mapping
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_lidar_mapping
      - name: Test slt_lidar_locator
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_lidar_locator
      - name: Test slt_imu_odometry
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_imu_odometry
      - name: Test slt_eskf_locator
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_eskf_locator
      - name: Test slt_graph_locator
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_graph_locator
