name: Build and Test
on:
  push:
    branches: [ humble ]
  pull_request:
    branches: [ humble ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pre install
        run: |
          /usr/bin/bash -c "apt-get update && apt-get install -y libunwind-dev libceres-dev"
      - name: Remove flake8-quotes for linter
        run: /usr/bin/bash -c "apt-get remove -y python3-flake8-quotes"
      - name: Build localization_for_autonomous_driving
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          skip-tests: true
      - name: Test slt_interface
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_interface
      - name: Test slt_common
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_common
      - name: Test slt_lidar_odometry
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_lidar_odometry
      - name: Test slt_lidar_mapping
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_lidar_mapping
      - name: Test slt_lidar_locator
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_lidar_locator
      - name: Test slt_imu_odometry
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_imu_odometry
      - name: Test slt_eskf_locator
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_eskf_locator
      - name: Test slt_lio_mapping
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_lio_mapping
      - name: Test slt_graph_locator
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh slt_graph_locator
